[package]
name = "rosu-pp"
version = "0.1.0"
edition = "2021"

[features]
default = []
tracing = ["rosu-map/tracing"]

[dependencies]
rosu-map = { path = "../rosu-map" }
thiserror = { version = "1.0.50" }