[package]
name = "rosu-pp"
version = "0.1.0"
edition = "2021"

[features]
default = []
sync = []
tracing = ["rosu-map/tracing"]

[dependencies]
rosu-map = { path = "../rosu-map" }
thiserror = { version = "1.0.50" }

[dev-dependencies]
proptest = "1.4.0"

[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3