name: Clippy and Tests

on:
  push:
    branches:
      - main
      - next
  pull_request:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        feature: [default, async_tokio, async_std]

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --no-default-features --features ${{ matrix.feature }}

  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        feature: [default, async_tokio, async_std]

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
    
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
  
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --no-default-features --features ${{ matrix.feature }} --no-fail-fast --failure-output=immediate-final
